language: minimal
after_success:
  - git clone https://${GH_TOKEN}github.com/chpmnrssll/demo-content.git
  - git clone https://${GH_TOKEN}@github.com/chpmnrssll/help-portal.git
  - cd help-portal
  # - git checkout -b deploy
  - cp -f ../demo-content/*.* .
  - git add .
  - git commit -m "GitBook content updated"
  - git push https://${GH_TOKEN}@github.com/chpmnrssll/help-portal.git
