language: minimal
after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - chmod 600 .travis/deploy_key.pem # this key should have push access
  - ssh-add .travis/deploy_key.pem
  - git clone https://${GH_TOKEN}@github.com/chpmnrssll/help-portal.git
  - cd ../help-portal
  - git checkout deploy
  - cp -f ../demo-content/*.*
  - git add .
  - git commit -m "deploy"
  - git push

  # - git config --global user.email "travis@travis-ci.org"
  # - git config --global user.name "Travis CI"
  # - git checkout -b gh-pages
  # - git add . *.html
  # - git commit --message "Travis build: $TRAVIS_BUILD_NUMBER"
  # - git remote add origin-pages https://${GH_TOKEN}@github.com/MVSE-outreach/resources.git > /dev/null 2>&1
  # - git push --quiet --set-upstream origin-pages gh-pages
