language: minimal
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install realpath python python-pip -y
  - sudo apt-get install --only-upgrade docker-ce -y
  - sudo apt-get install tree -y
after_success:
  - tree 
  - mkdir .build/md2html2/demo-content
  - cp -r * .build/md2html2/demo-content/
  - cd .build/md2html2/
  - docker build -t build-help-site  .  
  - docker run -dit --name build-help-site-live build-help-site        
  - cd ../apache2
  - docker cp build-help-site-live:/build/_site help-portal/
  - docker stop build-help-site-live
  - docker build -t help-site .
  - docker images -a
  - echo "$ARTIFACT_PASSWORD" | docker login -u "$ARTIFACT_USERNAME" --password-stdin
  - docker tag help-site $ARTIFACT_USERNAME/help-site
  - docker push $ARTIFACT_USERNAME/help-site