language: minimal
after_success:
  - git clone https://${GH_TOKEN}@github.com/chpmnrssll/help-portal.git
  - cd help-portal
  - git checkout -b "Build"
  - shopt -s extglob
  - cp -rf ../!(help-portal) .
  - git add .
  - git commit -m "GitBook content updated"
  - git push -u https://${GH_TOKEN}@github.com/chpmnrssll/help-portal.git Build
